<?php
/**
 * Created by PhpStorm.
 * User: leila
 * Date: 20/05/2020
 * Time: 10:44
 */


require_once 'BaseController.php';
require_once __DIR__.'/../models/ProductModel.php';
class ProductsController extends BaseController
{
    function __construct(){
        parent::__construct();
        $this->model = new ProductModel();
    }


    public function getFilters()
    {
        $filters = parent::getFilters(); // TODO: Change the autogenerated stub
        if(isset($_GET['query']) && !empty($_GET['query'])){
            $filters[] = 'name like "%'.$_GET['query'].'%"';
        }
        return $filters;
    }
}