<?php
/**
 * Created by PhpStorm.
 * User: leila
 * Date: 20/05/2020
 * Time: 10:44
 */


require_once 'BaseController.php';
require_once __DIR__.'/../models/ProductModel.php';
class ProductsController extends BaseController
{
    function __construct(){
        parent::__construct();
        $this->model = new ProductModel();
    }


    public function getFilters()
    {
        $filters = parent::getFilters(); // TODO: Change the autogenerated stub
        if(isset($_GET['query']) && !empty($_GET['query'])){
            $filters[] = 'name like "%'.$_GET['query'].'%"';
        }
        return $filters;
    }

    function getTotProducts(){
        $this->returnSuccess(200,$this->model->countProducts());
    }

    public function delete()
    {
        //esto es para que si se borran productos, y uno accede a un pedido viejo, el id del producto siga existiendo

        if(isset($_GET['id'])){
            $product= $this->model->findById($_GET['id']);
            $this->model->update($product['id'],array('state'=> "dead"));
        }

        // parent::delete(); // TODO: Change the autogenerated stub
    }
}